// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'changes/models/discount_model.dart';
import 'changes/models/product_discount_model.dart';
import 'features/hive_repository/tiin/singletons/api/clear_receipt/model/clear_receipt_model_8.dart';
import 'features/hive_repository/tiin/singletons/api/receipt/model/receipt_model_8.dart';
import 'features/hive_repository/tiin/singletons/api/receipt_4/model/receipt_model_4.dart';
import 'features/hive_repository/tiin/singletons/api/shift_4/model/rule_cash_model_4.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6813316753278961855),
      name: 'ClearReceiptModel8',
      lastPropertyId: const obx_int.IdUid(6, 462603684362972583),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3699115449736494766),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7001394832338390011),
            name: 'cashierName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4874173226158856468),
            name: 'cashierPhone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2277684591034390337),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3066311570827095255),
            name: 'total',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 462603684362972583),
            name: 'uploaded',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4292881946857715535),
      name: 'DiscountModel',
      lastPropertyId: const obx_int.IdUid(6, 6092482277300871571),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2422332278494823679),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 431655078538879139),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3395394388475719561),
            name: 'value',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8983825576817985512),
            name: 'total',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6165653109988402756),
            name: 'idd',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6092482277300871571),
            name: 'type',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 3601186149013975851),
      name: 'ReceiptModel4',
      lastPropertyId: const obx_int.IdUid(46, 5702815142943518960),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2563636278945499663),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6355383097060434417),
            name: 'newid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8024823785188027286),
            name: 'cashierId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1351354568237619964),
            name: 'cashierName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5731077170272284848),
            name: 'date',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4394384236944228099),
            name: 'isRefund',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5693417325130192388),
            name: 'totalPrice',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1742954311188471556),
            name: 'uploaded',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8978744828145437328),
            name: 'rejected',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6372369879907710637),
            name: 'clientName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5778371192464488434),
            name: 'clientPhone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7790570679357744076),
            name: 'cashback',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5782584921707514582),
            name: 'sdacha',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 6845162217192335150),
            name: 'returnForCheck',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2662069800776697177),
            name: 'posName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1218854897747008346),
            name: 'zdachiToCashback',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 1783931813957107536),
            name: 'refundInfo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 5980843119357437347),
            name: 'commissionTIN',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 4213250984406093057),
            name: 'hasClick',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 1083554468428618093),
            name: 'hasUzum',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 3616623968503448170),
            name: 'hasPayme',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 6108981735566772259),
            name: 'terminalId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 4734880103684383951),
            name: 'receiptSeq',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 6929463051331807865),
            name: 'dateTimeOFD',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 8722296207822480436),
            name: 'fiscalSign',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 4248425707081858313),
            name: 'orderId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 2902401735649644626),
            name: 'createdDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 2245421917012878436),
            name: 'cashboxId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(29, 2661653423790607013),
            name: 'externalId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(30, 3000764001679747134),
            name: 'clientId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(31, 8152868947206576368),
            name: 'discountID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(32, 1641354275054983582),
            name: 'discountVat',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(33, 1055057468756780143),
            name: 'orderType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(34, 2591900970901888285),
            name: 'shopId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(35, 401173544840968816),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(36, 3957274726200956307),
            name: 'isDonate',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(37, 8684118077598692222),
            name: 'comment',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(38, 3257921871780040069),
            name: 'isShow',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(39, 966856535640834235),
            name: 'hasDept',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(42, 1651857100672149695),
            name: 'url',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(43, 1225267735413651745),
            name: 'supplierId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(44, 2418026417945809955),
            name: 'cardNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(45, 7164971471029930497),
            name: 'pptId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(46, 5702815142943518960),
            name: 'cardType',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 4922301203481440764),
            name: 'soldItemList',
            targetId: const obx_int.IdUid(7, 4121567817909813718)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 7834158688311113142),
            name: 'payment',
            targetId: const obx_int.IdUid(6, 4228972988315566177))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3404640782702005997),
      name: 'ReceiptModel8',
      lastPropertyId: const obx_int.IdUid(7, 1084127504968914533),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5814107624379946298),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7873687077712527627),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 827647639181896857),
            name: 'client',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1727067650967103139),
            name: 'cashback',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3043290141604854500),
            name: 'type',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9109251424060568529),
            name: 'createdDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1084127504968914533),
            name: 'uploaded',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 115628913915853496),
            name: 'items',
            targetId: const obx_int.IdUid(5, 7181186939034080260))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7181186939034080260),
      name: 'ReceiptModelItem8',
      lastPropertyId: const obx_int.IdUid(6, 475086943868755625),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5161827775394309313),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7171106399584978365),
            name: 'sku',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2028189703721999446),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5661235824253020389),
            name: 'qty',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1851524808374094274),
            name: 'pricePosition',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 475086943868755625),
            name: 'value',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 4228972988315566177),
      name: 'ReceiptModelPaymentType4',
      lastPropertyId: const obx_int.IdUid(4, 4588355747873348010),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1798224794897548175),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2454935817978800031),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8235862340735752584),
            name: 'payId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4588355747873348010),
            name: 'value',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 4121567817909813718),
      name: 'ReceiptModelSoldItem4',
      lastPropertyId: const obx_int.IdUid(41, 7753485730070532226),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6745657717820839922),
            name: 'orderId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7441596904966562530),
            name: 'refundItemId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4500355667222721834),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6448137061425777037),
            name: 'realPrice',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5398555112398884226),
            name: 'onlyPrice',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4857410239986480486),
            name: 'singleDiscount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 336885971818026313),
            name: 'barcode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1276453026535488112),
            name: 'productId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5028357298880623912),
            name: 'mxik',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8898550540896712435),
            name: 'productName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3814573572411625741),
            name: 'sku',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 554748851872409365),
            name: 'sellerId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4277287193119582995),
            name: 'cost',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 9053856433042137090),
            name: 'totalDiscountPrice',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 1363315015089211359),
            name: 'value',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 2312738311681275315),
            name: 'vatName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 8440350234471194191),
            name: 'vat',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 8651462218516244114),
            name: 'vatPercent',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 1255436144492786775),
            name: 'packageCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 1825561387543404209),
            name: 'packageName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 7020084911398784994),
            name: 'commissionTIN',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 8271594360924768599),
            name: 'isPriceChanged',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 175472030309452750),
            name: 'isPriceOnlyChanged',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 5829683517309055481),
            name: 'createdTime',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 3733693976422908105),
            name: 'inBox',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 8559915727535040092),
            name: 'tin',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 4569093510262188548),
            name: 'marking',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 5065314961126606099),
            name: 'mark',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(29, 2468884685200739693),
            name: 'mxikError',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(30, 6257119440324995498),
            name: 'discountPercent',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(31, 2949084338530605458),
            name: 'isDeleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(32, 5574585626460212703),
            name: 'soldBy',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(33, 6738731039376024412),
            name: 'ownerType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(34, 7711210467784837203),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(35, 5494909870055592427),
            name: 'isKg',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(36, 4906907445883140393),
            name: 'isFreeGift',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(37, 5698506285208245560),
            name: 'productType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(38, 1742047357587076320),
            name: 'productPackage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(39, 7034426403519152331),
            name: 'saleType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(40, 1877520802038796105),
            name: 'boxValue',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(41, 7753485730070532226),
            name: 'boxQuantity',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(4, 3993923698123731774),
            name: 'discount',
            targetId: const obx_int.IdUid(2, 4292881946857715535)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(5, 6940710017558974671),
            name: 'productDiscount',
            targetId: const obx_int.IdUid(9, 5307975502303202672))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 4756499222689437799),
      name: 'RuleCashModel4',
      lastPropertyId: const obx_int.IdUid(7, 8506857492948778125),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 823547402373913662),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4245136471587453809),
            name: 'time',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6528467933194075758),
            name: 'cashierName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9018817355600296299),
            name: 'note',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1907411465553442750),
            name: 'money',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1167730292848741842),
            name: 'isIncome',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8506857492948778125),
            name: 'cashType',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 5307975502303202672),
      name: 'ProductDiscountModel',
      lastPropertyId: const obx_int.IdUid(7, 6238804638014968151),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4312664178536633901),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6535121135522101836),
            name: 'idd',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3148058204395609312),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1216308399272423995),
            name: 'typeName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7037762818785244663),
            name: 'value',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8604482945225327801),
            name: 'typeId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6238804638014968151),
            name: 'total',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(10, 1999358349783472865),
      name: 'ReceiptModelOFD4',
      lastPropertyId: const obx_int.IdUid(5, 6936574148170150807),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4283898342785514988),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8825167026845029368),
            name: 'receiptSeq',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6734893685480405814),
            name: 'dateTime',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1642108623064036097),
            name: 'terminalId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6936574148170150807),
            name: 'fiscalSign',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(10, 1999358349783472865),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(5, 6940710017558974671),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        2598214320627235180,
        2429788522452709675,
        7662243609673276694
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ClearReceiptModel8: obx_int.EntityDefinition<ClearReceiptModel8>(
        model: _entities[0],
        toOneRelations: (ClearReceiptModel8 object) => [],
        toManyRelations: (ClearReceiptModel8 object) => {},
        getId: (ClearReceiptModel8 object) => object.id,
        setId: (ClearReceiptModel8 object, int id) {
          object.id = id;
        },
        objectToFB: (ClearReceiptModel8 object, fb.Builder fbb) {
          final cashierNameOffset = fbb.writeString(object.cashierName);
          final cashierPhoneOffset = fbb.writeString(object.cashierPhone);
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, cashierNameOffset);
          fbb.addOffset(2, cashierPhoneOffset);
          fbb.addOffset(3, contentOffset);
          fbb.addInt64(4, object.total);
          fbb.addBool(5, object.uploaded);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final cashierNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final cashierPhoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final totalParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final uploadedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final object = ClearReceiptModel8(
              cashierName: cashierNameParam,
              cashierPhone: cashierPhoneParam,
              content: contentParam,
              total: totalParam,
              uploaded: uploadedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DiscountModel: obx_int.EntityDefinition<DiscountModel>(
        model: _entities[1],
        toOneRelations: (DiscountModel object) => [],
        toManyRelations: (DiscountModel object) => {},
        getId: (DiscountModel object) => object.id,
        setId: (DiscountModel object, int id) {
          object.id = id;
        },
        objectToFB: (DiscountModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final iddOffset = fbb.writeString(object.idd);
          final typeOffset = fbb.writeString(object.type);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.value);
          fbb.addFloat64(3, object.total);
          fbb.addOffset(4, iddOffset);
          fbb.addOffset(5, typeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final iddParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final totalParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final valueParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = DiscountModel(
              idd: iddParam,
              name: nameParam,
              total: totalParam,
              type: typeParam,
              value: valueParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ReceiptModel4: obx_int.EntityDefinition<ReceiptModel4>(
        model: _entities[2],
        toOneRelations: (ReceiptModel4 object) => [],
        toManyRelations: (ReceiptModel4 object) => {
              obx_int.RelInfo<ReceiptModel4>.toMany(1, object.id):
                  object.soldItemList,
              obx_int.RelInfo<ReceiptModel4>.toMany(2, object.id):
                  object.payment
            },
        getId: (ReceiptModel4 object) => object.id,
        setId: (ReceiptModel4 object, int id) {
          object.id = id;
        },
        objectToFB: (ReceiptModel4 object, fb.Builder fbb) {
          final newidOffset = fbb.writeString(object.newid);
          final cashierIdOffset = fbb.writeString(object.cashierId);
          final cashierNameOffset = fbb.writeString(object.cashierName);
          final clientNameOffset = fbb.writeString(object.clientName);
          final clientPhoneOffset = fbb.writeString(object.clientPhone);
          final returnForCheckOffset = fbb.writeString(object.returnForCheck);
          final posNameOffset = fbb.writeString(object.posName);
          final refundInfoOffset = object.refundInfo == null
              ? null
              : fbb.writeString(object.refundInfo!);
          final commissionTINOffset = object.commissionTIN == null
              ? null
              : fbb.writeString(object.commissionTIN!);
          final terminalIdOffset = object.terminalId == null
              ? null
              : fbb.writeString(object.terminalId!);
          final dateTimeOFDOffset = object.dateTimeOFD == null
              ? null
              : fbb.writeString(object.dateTimeOFD!);
          final fiscalSignOffset = object.fiscalSign == null
              ? null
              : fbb.writeString(object.fiscalSign!);
          final orderIdOffset = fbb.writeString(object.orderId);
          final createdDateOffset = fbb.writeString(object.createdDate);
          final cashboxIdOffset = fbb.writeString(object.cashboxId);
          final externalIdOffset = fbb.writeString(object.externalId);
          final clientIdOffset = fbb.writeString(object.clientId);
          final discountIDOffset = fbb.writeString(object.discountID);
          final orderTypeOffset = fbb.writeString(object.orderType);
          final shopIdOffset = fbb.writeString(object.shopId);
          final userIdOffset = fbb.writeString(object.userId);
          final commentOffset =
              object.comment == null ? null : fbb.writeString(object.comment!);
          final urlOffset =
              object.url == null ? null : fbb.writeString(object.url!);
          final supplierIdOffset = fbb.writeString(object.supplierId);
          final cardNumberOffset = object.cardNumber == null
              ? null
              : fbb.writeString(object.cardNumber!);
          final pptIdOffset =
              object.pptId == null ? null : fbb.writeString(object.pptId!);
          fbb.startTable(47);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, newidOffset);
          fbb.addOffset(2, cashierIdOffset);
          fbb.addOffset(3, cashierNameOffset);
          fbb.addInt64(4, object.date);
          fbb.addBool(5, object.isRefund);
          fbb.addFloat64(6, object.totalPrice);
          fbb.addBool(7, object.uploaded);
          fbb.addBool(8, object.rejected);
          fbb.addOffset(9, clientNameOffset);
          fbb.addOffset(10, clientPhoneOffset);
          fbb.addInt64(11, object.cashback);
          fbb.addFloat64(12, object.sdacha);
          fbb.addOffset(13, returnForCheckOffset);
          fbb.addOffset(14, posNameOffset);
          fbb.addFloat64(15, object.zdachiToCashback);
          fbb.addOffset(16, refundInfoOffset);
          fbb.addOffset(17, commissionTINOffset);
          fbb.addBool(18, object.hasClick);
          fbb.addBool(19, object.hasUzum);
          fbb.addBool(20, object.hasPayme);
          fbb.addOffset(21, terminalIdOffset);
          fbb.addInt64(22, object.receiptSeq);
          fbb.addOffset(23, dateTimeOFDOffset);
          fbb.addOffset(24, fiscalSignOffset);
          fbb.addOffset(25, orderIdOffset);
          fbb.addOffset(26, createdDateOffset);
          fbb.addOffset(27, cashboxIdOffset);
          fbb.addOffset(28, externalIdOffset);
          fbb.addOffset(29, clientIdOffset);
          fbb.addOffset(30, discountIDOffset);
          fbb.addFloat64(31, object.discountVat);
          fbb.addOffset(32, orderTypeOffset);
          fbb.addOffset(33, shopIdOffset);
          fbb.addOffset(34, userIdOffset);
          fbb.addBool(35, object.isDonate);
          fbb.addOffset(36, commentOffset);
          fbb.addBool(37, object.isShow);
          fbb.addBool(38, object.hasDept);
          fbb.addOffset(41, urlOffset);
          fbb.addOffset(42, supplierIdOffset);
          fbb.addOffset(43, cardNumberOffset);
          fbb.addOffset(44, pptIdOffset);
          fbb.addInt64(45, object.cardType);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 56, '');
          final orderIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 54, '');
          final cashboxIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 58, '');
          final externalIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 60, '');
          final orderTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 68, '');
          final shopIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 70, '');
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 72, '');
          final discountVatParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 66, 0);
          final discountIDParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 64, '');
          final urlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 86);
          final terminalIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 46);
          final receiptSeqParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 48);
          final dateTimeOFDParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final fiscalSignParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 52);
          final zdachiToCashbackParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 34);
          final newidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final cashierIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final cashierNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final dateParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final isRefundParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final totalPriceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final uploadedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final rejectedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final clientNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final clientPhoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final clientIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 62, '');
          final supplierIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 88, '');
          final cashbackParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final sdachaParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final returnForCheckParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 30, '');
          final posNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 32, '');
          final refundInfoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 36);
          final commissionTINParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 38);
          final hasClickParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 40, false);
          final hasUzumParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 42, false);
          final hasPaymeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 44, false);
          final isShowParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 78);
          final commentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 76);
          final isDonateParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 74);
          final cardNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 90);
          final cardTypeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 94);
          final pptIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 92);
          final object = ReceiptModel4(
              createdDate: createdDateParam,
              orderId: orderIdParam,
              cashboxId: cashboxIdParam,
              externalId: externalIdParam,
              orderType: orderTypeParam,
              shopId: shopIdParam,
              userId: userIdParam,
              discountVat: discountVatParam,
              discountID: discountIDParam,
              url: urlParam,
              terminalId: terminalIdParam,
              receiptSeq: receiptSeqParam,
              dateTimeOFD: dateTimeOFDParam,
              fiscalSign: fiscalSignParam,
              zdachiToCashback: zdachiToCashbackParam,
              newid: newidParam,
              cashierId: cashierIdParam,
              cashierName: cashierNameParam,
              date: dateParam,
              isRefund: isRefundParam,
              totalPrice: totalPriceParam,
              uploaded: uploadedParam,
              rejected: rejectedParam,
              clientName: clientNameParam,
              clientPhone: clientPhoneParam,
              clientId: clientIdParam,
              supplierId: supplierIdParam,
              cashback: cashbackParam,
              sdacha: sdachaParam,
              returnForCheck: returnForCheckParam,
              posName: posNameParam,
              refundInfo: refundInfoParam,
              commissionTIN: commissionTINParam,
              hasClick: hasClickParam,
              hasUzum: hasUzumParam,
              hasPayme: hasPaymeParam,
              isShow: isShowParam,
              comment: commentParam,
              isDonate: isDonateParam,
              cardNumber: cardNumberParam,
              cardType: cardTypeParam,
              pptId: pptIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..hasDept =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 80, false);
          obx_int.InternalToManyAccess.setRelInfo<ReceiptModel4>(
              object.soldItemList,
              store,
              obx_int.RelInfo<ReceiptModel4>.toMany(1, object.id));
          obx_int.InternalToManyAccess.setRelInfo<ReceiptModel4>(object.payment,
              store, obx_int.RelInfo<ReceiptModel4>.toMany(2, object.id));
          return object;
        }),
    ReceiptModel8: obx_int.EntityDefinition<ReceiptModel8>(
        model: _entities[3],
        toOneRelations: (ReceiptModel8 object) => [],
        toManyRelations: (ReceiptModel8 object) =>
            {obx_int.RelInfo<ReceiptModel8>.toMany(3, object.id): object.items},
        getId: (ReceiptModel8 object) => object.id,
        setId: (ReceiptModel8 object, int id) {
          object.id = id;
        },
        objectToFB: (ReceiptModel8 object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final clientOffset = fbb.writeString(object.client);
          final createdDateOffset = fbb.writeString(object.createdDate);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, clientOffset);
          fbb.addInt64(3, object.cashback);
          fbb.addInt64(4, object.type);
          fbb.addOffset(5, createdDateOffset);
          fbb.addInt64(6, object.uploaded);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final clientParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final cashbackParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final typeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final createdDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final uploadedParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = ReceiptModel8(
              name: nameParam,
              client: clientParam,
              cashback: cashbackParam,
              type: typeParam,
              createdDate: createdDateParam,
              uploaded: uploadedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<ReceiptModel8>(object.items,
              store, obx_int.RelInfo<ReceiptModel8>.toMany(3, object.id));
          return object;
        }),
    ReceiptModelItem8: obx_int.EntityDefinition<ReceiptModelItem8>(
        model: _entities[4],
        toOneRelations: (ReceiptModelItem8 object) => [],
        toManyRelations: (ReceiptModelItem8 object) => {},
        getId: (ReceiptModelItem8 object) => object.id,
        setId: (ReceiptModelItem8 object, int id) {
          object.id = id;
        },
        objectToFB: (ReceiptModelItem8 object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.sku);
          fbb.addOffset(2, nameOffset);
          fbb.addFloat64(3, object.qty);
          fbb.addInt64(4, object.pricePosition);
          fbb.addFloat64(5, object.value);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final skuParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final qtyParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final pricePositionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final valueParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = ReceiptModelItem8(
              name: nameParam,
              sku: skuParam,
              qty: qtyParam,
              pricePosition: pricePositionParam,
              value: valueParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ReceiptModelPaymentType4:
        obx_int.EntityDefinition<ReceiptModelPaymentType4>(
            model: _entities[5],
            toOneRelations: (ReceiptModelPaymentType4 object) => [],
            toManyRelations: (ReceiptModelPaymentType4 object) => {},
            getId: (ReceiptModelPaymentType4 object) => object.id,
            setId: (ReceiptModelPaymentType4 object, int id) {
              object.id = id;
            },
            objectToFB: (ReceiptModelPaymentType4 object, fb.Builder fbb) {
              final nameOffset = fbb.writeString(object.name);
              final payIdOffset = fbb.writeString(object.payId);
              fbb.startTable(5);
              fbb.addInt64(0, object.id);
              fbb.addOffset(1, nameOffset);
              fbb.addOffset(2, payIdOffset);
              fbb.addFloat64(3, object.value);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final nameParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
              final payIdParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
              final valueParam =
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
              final object = ReceiptModelPaymentType4(
                  name: nameParam, payId: payIdParam, value: valueParam)
                ..id =
                    const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

              return object;
            }),
    ReceiptModelSoldItem4: obx_int.EntityDefinition<ReceiptModelSoldItem4>(
        model: _entities[6],
        toOneRelations: (ReceiptModelSoldItem4 object) => [],
        toManyRelations: (ReceiptModelSoldItem4 object) => {
              obx_int.RelInfo<ReceiptModelSoldItem4>.toMany(4, object.id):
                  object.discount,
              obx_int.RelInfo<ReceiptModelSoldItem4>.toMany(5, object.id):
                  object.productDiscount
            },
        getId: (ReceiptModelSoldItem4 object) => object.id,
        setId: (ReceiptModelSoldItem4 object, int id) {
          object.id = id;
        },
        objectToFB: (ReceiptModelSoldItem4 object, fb.Builder fbb) {
          final orderIdOffset = fbb.writeString(object.orderId);
          final refundItemIdOffset = object.refundItemId == null
              ? null
              : fbb.writeString(object.refundItemId!);
          final barcodeOffset = fbb.writeString(object.barcode);
          final productIdOffset = fbb.writeString(object.productId);
          final mxikOffset = fbb.writeString(object.mxik);
          final productNameOffset = fbb.writeString(object.productName);
          final sellerIdOffset = fbb.writeString(object.sellerId);
          final vatNameOffset = fbb.writeString(object.vatName);
          final packageCodeOffset = object.packageCode == null
              ? null
              : fbb.writeString(object.packageCode!);
          final packageNameOffset = object.packageName == null
              ? null
              : fbb.writeString(object.packageName!);
          final commissionTINOffset = object.commissionTIN == null
              ? null
              : fbb.writeString(object.commissionTIN!);
          final tinOffset =
              object.tin == null ? null : fbb.writeString(object.tin!);
          final markOffset =
              object.mark == null ? null : fbb.writeString(object.mark!);
          final soldByOffset = fbb.writeString(object.soldBy);
          final productTypeOffset = fbb.writeString(object.productType);
          final productPackageOffset = fbb.writeString(object.productPackage);
          fbb.startTable(42);
          fbb.addOffset(0, orderIdOffset);
          fbb.addOffset(1, refundItemIdOffset);
          fbb.addFloat64(2, object.price);
          fbb.addFloat64(3, object.realPrice);
          fbb.addFloat64(4, object.onlyPrice);
          fbb.addFloat64(5, object.singleDiscount);
          fbb.addOffset(6, barcodeOffset);
          fbb.addOffset(7, productIdOffset);
          fbb.addOffset(8, mxikOffset);
          fbb.addOffset(9, productNameOffset);
          fbb.addInt64(10, object.sku);
          fbb.addOffset(11, sellerIdOffset);
          fbb.addFloat64(12, object.cost);
          fbb.addFloat64(13, object.totalDiscountPrice);
          fbb.addFloat64(14, object.value);
          fbb.addOffset(15, vatNameOffset);
          fbb.addFloat64(16, object.vat);
          fbb.addFloat64(17, object.vatPercent);
          fbb.addOffset(18, packageCodeOffset);
          fbb.addOffset(19, packageNameOffset);
          fbb.addOffset(20, commissionTINOffset);
          fbb.addBool(21, object.isPriceChanged);
          fbb.addBool(22, object.isPriceOnlyChanged);
          fbb.addInt64(23, object.createdTime);
          fbb.addInt64(24, object.inBox);
          fbb.addOffset(25, tinOffset);
          fbb.addBool(26, object.marking);
          fbb.addOffset(27, markOffset);
          fbb.addBool(28, object.mxikError);
          fbb.addFloat64(29, object.discountPercent);
          fbb.addBool(30, object.isDeleted);
          fbb.addOffset(31, soldByOffset);
          fbb.addInt64(32, object.ownerType);
          fbb.addInt64(33, object.id);
          fbb.addBool(34, object.isKg);
          fbb.addBool(35, object.isFreeGift);
          fbb.addOffset(36, productTypeOffset);
          fbb.addOffset(37, productPackageOffset);
          fbb.addInt64(38, object.saleType);
          fbb.addInt64(39, object.boxValue);
          fbb.addInt64(40, object.boxQuantity);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final inBoxParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 52, 0);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final skuParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final vatPercentParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 38, 0);
          final vatParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 36, 0);
          final mxikParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final tinParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 54);
          final onlyPriceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final realPriceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final costParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final vatNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 34, '');
          final createdTimeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 50, 0);
          final valueParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 32, 0);
          final productIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final productNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, '');
          final sellerIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final soldByParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 66, '');
          final singleDiscountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final ownerTypeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 68);
          final isDeletedParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 64);
          final commissionTINParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 44);
          final mxikErrorParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 60);
          final totalDiscountPriceParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 30);
          final markParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 58);
          final refundItemIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final markingParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 56, false);
          final discountPercentParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 62);
          final isPriceChangedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 46, false);
          final isPriceOnlyChangedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 48, false);
          final isKgParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 72, false);
          final packageCodeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 40);
          final packageNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 42);
          final isFreeGiftParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 74, false);
          final productTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 76, '');
          final productPackageParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 78, '');
          final saleTypeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 80, 0);
          final boxValueParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 82, 0);
          final boxQuantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 84, 0);
          final object = ReceiptModelSoldItem4(
              inBox: inBoxParam,
              barcode: barcodeParam,
              sku: skuParam,
              vatPercent: vatPercentParam,
              vat: vatParam,
              mxik: mxikParam,
              tin: tinParam,
              onlyPrice: onlyPriceParam,
              realPrice: realPriceParam,
              price: priceParam,
              cost: costParam,
              vatName: vatNameParam,
              createdTime: createdTimeParam,
              value: valueParam,
              productId: productIdParam,
              productName: productNameParam,
              sellerId: sellerIdParam,
              soldBy: soldByParam,
              singleDiscount: singleDiscountParam,
              ownerType: ownerTypeParam,
              isDeleted: isDeletedParam,
              commissionTIN: commissionTINParam,
              mxikError: mxikErrorParam,
              totalDiscountPrice: totalDiscountPriceParam,
              mark: markParam,
              refundItemId: refundItemIdParam,
              marking: markingParam,
              discountPercent: discountPercentParam,
              isPriceChanged: isPriceChangedParam,
              isPriceOnlyChanged: isPriceOnlyChangedParam,
              isKg: isKgParam,
              packageCode: packageCodeParam,
              packageName: packageNameParam,
              isFreeGift: isFreeGiftParam,
              productType: productTypeParam,
              productPackage: productPackageParam,
              saleType: saleTypeParam,
              boxValue: boxValueParam,
              boxQuantity: boxQuantityParam)
            ..orderId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 70, 0);
          obx_int.InternalToManyAccess.setRelInfo<ReceiptModelSoldItem4>(
              object.discount,
              store,
              obx_int.RelInfo<ReceiptModelSoldItem4>.toMany(4, object.id));
          obx_int.InternalToManyAccess.setRelInfo<ReceiptModelSoldItem4>(
              object.productDiscount,
              store,
              obx_int.RelInfo<ReceiptModelSoldItem4>.toMany(5, object.id));
          return object;
        }),
    RuleCashModel4: obx_int.EntityDefinition<RuleCashModel4>(
        model: _entities[7],
        toOneRelations: (RuleCashModel4 object) => [],
        toManyRelations: (RuleCashModel4 object) => {},
        getId: (RuleCashModel4 object) => object.id,
        setId: (RuleCashModel4 object, int id) {
          object.id = id;
        },
        objectToFB: (RuleCashModel4 object, fb.Builder fbb) {
          final timeOffset = fbb.writeString(object.time);
          final cashierNameOffset = fbb.writeString(object.cashierName);
          final noteOffset = fbb.writeString(object.note);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, timeOffset);
          fbb.addOffset(2, cashierNameOffset);
          fbb.addOffset(3, noteOffset);
          fbb.addFloat64(4, object.money);
          fbb.addBool(5, object.isIncome);
          fbb.addInt64(6, object.cashType);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final cashierNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final noteParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final moneyParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final isIncomeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final cashTypeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = RuleCashModel4(
              time: timeParam,
              cashierName: cashierNameParam,
              note: noteParam,
              money: moneyParam,
              isIncome: isIncomeParam,
              cashType: cashTypeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ProductDiscountModel: obx_int.EntityDefinition<ProductDiscountModel>(
        model: _entities[8],
        toOneRelations: (ProductDiscountModel object) => [],
        toManyRelations: (ProductDiscountModel object) => {},
        getId: (ProductDiscountModel object) => object.id,
        setId: (ProductDiscountModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductDiscountModel object, fb.Builder fbb) {
          final iddOffset = fbb.writeString(object.idd);
          final nameOffset = fbb.writeString(object.name);
          final typeNameOffset = fbb.writeString(object.typeName);
          final typeIdOffset = fbb.writeString(object.typeId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, iddOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, typeNameOffset);
          fbb.addFloat64(4, object.value);
          fbb.addOffset(5, typeIdOffset);
          fbb.addFloat64(6, object.total);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final iddParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final typeIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final typeNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final valueParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final totalParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = ProductDiscountModel(
              idd: iddParam,
              typeId: typeIdParam,
              typeName: typeNameParam,
              name: nameParam,
              value: valueParam,
              total: totalParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ReceiptModelOFD4: obx_int.EntityDefinition<ReceiptModelOFD4>(
        model: _entities[9],
        toOneRelations: (ReceiptModelOFD4 object) => [],
        toManyRelations: (ReceiptModelOFD4 object) => {},
        getId: (ReceiptModelOFD4 object) => object.id,
        setId: (ReceiptModelOFD4 object, int id) {
          object.id = id;
        },
        objectToFB: (ReceiptModelOFD4 object, fb.Builder fbb) {
          final terminalIdOffset = object.terminalId == null
              ? null
              : fbb.writeString(object.terminalId!);
          final fiscalSignOffset = object.fiscalSign == null
              ? null
              : fbb.writeString(object.fiscalSign!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.receiptSeq);
          fbb.addInt64(2, object.dateTime);
          fbb.addOffset(3, terminalIdOffset);
          fbb.addOffset(4, fiscalSignOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateTimeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final fiscalSignParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final receiptSeqParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final terminalIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = ReceiptModelOFD4(
              dateTime: dateTimeParam,
              fiscalSign: fiscalSignParam,
              receiptSeq: receiptSeqParam,
              terminalId: terminalIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ClearReceiptModel8] entity fields to define ObjectBox queries.
class ClearReceiptModel8_ {
  /// see [ClearReceiptModel8.id]
  static final id =
      obx.QueryIntegerProperty<ClearReceiptModel8>(_entities[0].properties[0]);

  /// see [ClearReceiptModel8.cashierName]
  static final cashierName =
      obx.QueryStringProperty<ClearReceiptModel8>(_entities[0].properties[1]);

  /// see [ClearReceiptModel8.cashierPhone]
  static final cashierPhone =
      obx.QueryStringProperty<ClearReceiptModel8>(_entities[0].properties[2]);

  /// see [ClearReceiptModel8.content]
  static final content =
      obx.QueryStringProperty<ClearReceiptModel8>(_entities[0].properties[3]);

  /// see [ClearReceiptModel8.total]
  static final total =
      obx.QueryIntegerProperty<ClearReceiptModel8>(_entities[0].properties[4]);

  /// see [ClearReceiptModel8.uploaded]
  static final uploaded =
      obx.QueryBooleanProperty<ClearReceiptModel8>(_entities[0].properties[5]);
}

/// [DiscountModel] entity fields to define ObjectBox queries.
class DiscountModel_ {
  /// see [DiscountModel.id]
  static final id =
      obx.QueryIntegerProperty<DiscountModel>(_entities[1].properties[0]);

  /// see [DiscountModel.name]
  static final name =
      obx.QueryStringProperty<DiscountModel>(_entities[1].properties[1]);

  /// see [DiscountModel.value]
  static final value =
      obx.QueryDoubleProperty<DiscountModel>(_entities[1].properties[2]);

  /// see [DiscountModel.total]
  static final total =
      obx.QueryDoubleProperty<DiscountModel>(_entities[1].properties[3]);

  /// see [DiscountModel.idd]
  static final idd =
      obx.QueryStringProperty<DiscountModel>(_entities[1].properties[4]);

  /// see [DiscountModel.type]
  static final type =
      obx.QueryStringProperty<DiscountModel>(_entities[1].properties[5]);
}

/// [ReceiptModel4] entity fields to define ObjectBox queries.
class ReceiptModel4_ {
  /// see [ReceiptModel4.id]
  static final id =
      obx.QueryIntegerProperty<ReceiptModel4>(_entities[2].properties[0]);

  /// see [ReceiptModel4.newid]
  static final newid =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[1]);

  /// see [ReceiptModel4.cashierId]
  static final cashierId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[2]);

  /// see [ReceiptModel4.cashierName]
  static final cashierName =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[3]);

  /// see [ReceiptModel4.date]
  static final date =
      obx.QueryIntegerProperty<ReceiptModel4>(_entities[2].properties[4]);

  /// see [ReceiptModel4.isRefund]
  static final isRefund =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[5]);

  /// see [ReceiptModel4.totalPrice]
  static final totalPrice =
      obx.QueryDoubleProperty<ReceiptModel4>(_entities[2].properties[6]);

  /// see [ReceiptModel4.uploaded]
  static final uploaded =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[7]);

  /// see [ReceiptModel4.rejected]
  static final rejected =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[8]);

  /// see [ReceiptModel4.clientName]
  static final clientName =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[9]);

  /// see [ReceiptModel4.clientPhone]
  static final clientPhone =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[10]);

  /// see [ReceiptModel4.cashback]
  static final cashback =
      obx.QueryIntegerProperty<ReceiptModel4>(_entities[2].properties[11]);

  /// see [ReceiptModel4.sdacha]
  static final sdacha =
      obx.QueryDoubleProperty<ReceiptModel4>(_entities[2].properties[12]);

  /// see [ReceiptModel4.returnForCheck]
  static final returnForCheck =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[13]);

  /// see [ReceiptModel4.posName]
  static final posName =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[14]);

  /// see [ReceiptModel4.zdachiToCashback]
  static final zdachiToCashback =
      obx.QueryDoubleProperty<ReceiptModel4>(_entities[2].properties[15]);

  /// see [ReceiptModel4.refundInfo]
  static final refundInfo =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[16]);

  /// see [ReceiptModel4.commissionTIN]
  static final commissionTIN =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[17]);

  /// see [ReceiptModel4.hasClick]
  static final hasClick =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[18]);

  /// see [ReceiptModel4.hasUzum]
  static final hasUzum =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[19]);

  /// see [ReceiptModel4.hasPayme]
  static final hasPayme =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[20]);

  /// see [ReceiptModel4.terminalId]
  static final terminalId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[21]);

  /// see [ReceiptModel4.receiptSeq]
  static final receiptSeq =
      obx.QueryIntegerProperty<ReceiptModel4>(_entities[2].properties[22]);

  /// see [ReceiptModel4.dateTimeOFD]
  static final dateTimeOFD =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[23]);

  /// see [ReceiptModel4.fiscalSign]
  static final fiscalSign =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[24]);

  /// see [ReceiptModel4.orderId]
  static final orderId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[25]);

  /// see [ReceiptModel4.createdDate]
  static final createdDate =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[26]);

  /// see [ReceiptModel4.cashboxId]
  static final cashboxId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[27]);

  /// see [ReceiptModel4.externalId]
  static final externalId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[28]);

  /// see [ReceiptModel4.clientId]
  static final clientId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[29]);

  /// see [ReceiptModel4.discountID]
  static final discountID =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[30]);

  /// see [ReceiptModel4.discountVat]
  static final discountVat =
      obx.QueryDoubleProperty<ReceiptModel4>(_entities[2].properties[31]);

  /// see [ReceiptModel4.orderType]
  static final orderType =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[32]);

  /// see [ReceiptModel4.shopId]
  static final shopId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[33]);

  /// see [ReceiptModel4.userId]
  static final userId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[34]);

  /// see [ReceiptModel4.isDonate]
  static final isDonate =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[35]);

  /// see [ReceiptModel4.comment]
  static final comment =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[36]);

  /// see [ReceiptModel4.isShow]
  static final isShow =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[37]);

  /// see [ReceiptModel4.hasDept]
  static final hasDept =
      obx.QueryBooleanProperty<ReceiptModel4>(_entities[2].properties[38]);

  /// see [ReceiptModel4.url]
  static final url =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[39]);

  /// see [ReceiptModel4.supplierId]
  static final supplierId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[40]);

  /// see [ReceiptModel4.cardNumber]
  static final cardNumber =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[41]);

  /// see [ReceiptModel4.pptId]
  static final pptId =
      obx.QueryStringProperty<ReceiptModel4>(_entities[2].properties[42]);

  /// see [ReceiptModel4.cardType]
  static final cardType =
      obx.QueryIntegerProperty<ReceiptModel4>(_entities[2].properties[43]);

  /// see [ReceiptModel4.soldItemList]
  static final soldItemList =
      obx.QueryRelationToMany<ReceiptModel4, ReceiptModelSoldItem4>(
          _entities[2].relations[0]);

  /// see [ReceiptModel4.payment]
  static final payment =
      obx.QueryRelationToMany<ReceiptModel4, ReceiptModelPaymentType4>(
          _entities[2].relations[1]);
}

/// [ReceiptModel8] entity fields to define ObjectBox queries.
class ReceiptModel8_ {
  /// see [ReceiptModel8.id]
  static final id =
      obx.QueryIntegerProperty<ReceiptModel8>(_entities[3].properties[0]);

  /// see [ReceiptModel8.name]
  static final name =
      obx.QueryStringProperty<ReceiptModel8>(_entities[3].properties[1]);

  /// see [ReceiptModel8.client]
  static final client =
      obx.QueryStringProperty<ReceiptModel8>(_entities[3].properties[2]);

  /// see [ReceiptModel8.cashback]
  static final cashback =
      obx.QueryIntegerProperty<ReceiptModel8>(_entities[3].properties[3]);

  /// see [ReceiptModel8.type]
  static final type =
      obx.QueryIntegerProperty<ReceiptModel8>(_entities[3].properties[4]);

  /// see [ReceiptModel8.createdDate]
  static final createdDate =
      obx.QueryStringProperty<ReceiptModel8>(_entities[3].properties[5]);

  /// see [ReceiptModel8.uploaded]
  static final uploaded =
      obx.QueryIntegerProperty<ReceiptModel8>(_entities[3].properties[6]);

  /// see [ReceiptModel8.items]
  static final items =
      obx.QueryRelationToMany<ReceiptModel8, ReceiptModelItem8>(
          _entities[3].relations[0]);
}

/// [ReceiptModelItem8] entity fields to define ObjectBox queries.
class ReceiptModelItem8_ {
  /// see [ReceiptModelItem8.id]
  static final id =
      obx.QueryIntegerProperty<ReceiptModelItem8>(_entities[4].properties[0]);

  /// see [ReceiptModelItem8.sku]
  static final sku =
      obx.QueryIntegerProperty<ReceiptModelItem8>(_entities[4].properties[1]);

  /// see [ReceiptModelItem8.name]
  static final name =
      obx.QueryStringProperty<ReceiptModelItem8>(_entities[4].properties[2]);

  /// see [ReceiptModelItem8.qty]
  static final qty =
      obx.QueryDoubleProperty<ReceiptModelItem8>(_entities[4].properties[3]);

  /// see [ReceiptModelItem8.pricePosition]
  static final pricePosition =
      obx.QueryIntegerProperty<ReceiptModelItem8>(_entities[4].properties[4]);

  /// see [ReceiptModelItem8.value]
  static final value =
      obx.QueryDoubleProperty<ReceiptModelItem8>(_entities[4].properties[5]);
}

/// [ReceiptModelPaymentType4] entity fields to define ObjectBox queries.
class ReceiptModelPaymentType4_ {
  /// see [ReceiptModelPaymentType4.id]
  static final id = obx.QueryIntegerProperty<ReceiptModelPaymentType4>(
      _entities[5].properties[0]);

  /// see [ReceiptModelPaymentType4.name]
  static final name = obx.QueryStringProperty<ReceiptModelPaymentType4>(
      _entities[5].properties[1]);

  /// see [ReceiptModelPaymentType4.payId]
  static final payId = obx.QueryStringProperty<ReceiptModelPaymentType4>(
      _entities[5].properties[2]);

  /// see [ReceiptModelPaymentType4.value]
  static final value = obx.QueryDoubleProperty<ReceiptModelPaymentType4>(
      _entities[5].properties[3]);
}

/// [ReceiptModelSoldItem4] entity fields to define ObjectBox queries.
class ReceiptModelSoldItem4_ {
  /// see [ReceiptModelSoldItem4.orderId]
  static final orderId = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[0]);

  /// see [ReceiptModelSoldItem4.refundItemId]
  static final refundItemId = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[1]);

  /// see [ReceiptModelSoldItem4.price]
  static final price = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[2]);

  /// see [ReceiptModelSoldItem4.realPrice]
  static final realPrice = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[3]);

  /// see [ReceiptModelSoldItem4.onlyPrice]
  static final onlyPrice = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[4]);

  /// see [ReceiptModelSoldItem4.singleDiscount]
  static final singleDiscount = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[5]);

  /// see [ReceiptModelSoldItem4.barcode]
  static final barcode = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[6]);

  /// see [ReceiptModelSoldItem4.productId]
  static final productId = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[7]);

  /// see [ReceiptModelSoldItem4.mxik]
  static final mxik = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[8]);

  /// see [ReceiptModelSoldItem4.productName]
  static final productName = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[9]);

  /// see [ReceiptModelSoldItem4.sku]
  static final sku = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[10]);

  /// see [ReceiptModelSoldItem4.sellerId]
  static final sellerId = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[11]);

  /// see [ReceiptModelSoldItem4.cost]
  static final cost = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[12]);

  /// see [ReceiptModelSoldItem4.totalDiscountPrice]
  static final totalDiscountPrice =
      obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
          _entities[6].properties[13]);

  /// see [ReceiptModelSoldItem4.value]
  static final value = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[14]);

  /// see [ReceiptModelSoldItem4.vatName]
  static final vatName = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[15]);

  /// see [ReceiptModelSoldItem4.vat]
  static final vat = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[16]);

  /// see [ReceiptModelSoldItem4.vatPercent]
  static final vatPercent = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[17]);

  /// see [ReceiptModelSoldItem4.packageCode]
  static final packageCode = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[18]);

  /// see [ReceiptModelSoldItem4.packageName]
  static final packageName = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[19]);

  /// see [ReceiptModelSoldItem4.commissionTIN]
  static final commissionTIN = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[20]);

  /// see [ReceiptModelSoldItem4.isPriceChanged]
  static final isPriceChanged = obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[21]);

  /// see [ReceiptModelSoldItem4.isPriceOnlyChanged]
  static final isPriceOnlyChanged =
      obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
          _entities[6].properties[22]);

  /// see [ReceiptModelSoldItem4.createdTime]
  static final createdTime = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[23]);

  /// see [ReceiptModelSoldItem4.inBox]
  static final inBox = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[24]);

  /// see [ReceiptModelSoldItem4.tin]
  static final tin = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[25]);

  /// see [ReceiptModelSoldItem4.marking]
  static final marking = obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[26]);

  /// see [ReceiptModelSoldItem4.mark]
  static final mark = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[27]);

  /// see [ReceiptModelSoldItem4.mxikError]
  static final mxikError = obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[28]);

  /// see [ReceiptModelSoldItem4.discountPercent]
  static final discountPercent = obx.QueryDoubleProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[29]);

  /// see [ReceiptModelSoldItem4.isDeleted]
  static final isDeleted = obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[30]);

  /// see [ReceiptModelSoldItem4.soldBy]
  static final soldBy = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[31]);

  /// see [ReceiptModelSoldItem4.ownerType]
  static final ownerType = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[32]);

  /// see [ReceiptModelSoldItem4.id]
  static final id = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[33]);

  /// see [ReceiptModelSoldItem4.isKg]
  static final isKg = obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[34]);

  /// see [ReceiptModelSoldItem4.isFreeGift]
  static final isFreeGift = obx.QueryBooleanProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[35]);

  /// see [ReceiptModelSoldItem4.productType]
  static final productType = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[36]);

  /// see [ReceiptModelSoldItem4.productPackage]
  static final productPackage = obx.QueryStringProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[37]);

  /// see [ReceiptModelSoldItem4.saleType]
  static final saleType = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[38]);

  /// see [ReceiptModelSoldItem4.boxValue]
  static final boxValue = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[39]);

  /// see [ReceiptModelSoldItem4.boxQuantity]
  static final boxQuantity = obx.QueryIntegerProperty<ReceiptModelSoldItem4>(
      _entities[6].properties[40]);

  /// see [ReceiptModelSoldItem4.discount]
  static final discount =
      obx.QueryRelationToMany<ReceiptModelSoldItem4, DiscountModel>(
          _entities[6].relations[0]);

  /// see [ReceiptModelSoldItem4.productDiscount]
  static final productDiscount =
      obx.QueryRelationToMany<ReceiptModelSoldItem4, ProductDiscountModel>(
          _entities[6].relations[1]);
}

/// [RuleCashModel4] entity fields to define ObjectBox queries.
class RuleCashModel4_ {
  /// see [RuleCashModel4.id]
  static final id =
      obx.QueryIntegerProperty<RuleCashModel4>(_entities[7].properties[0]);

  /// see [RuleCashModel4.time]
  static final time =
      obx.QueryStringProperty<RuleCashModel4>(_entities[7].properties[1]);

  /// see [RuleCashModel4.cashierName]
  static final cashierName =
      obx.QueryStringProperty<RuleCashModel4>(_entities[7].properties[2]);

  /// see [RuleCashModel4.note]
  static final note =
      obx.QueryStringProperty<RuleCashModel4>(_entities[7].properties[3]);

  /// see [RuleCashModel4.money]
  static final money =
      obx.QueryDoubleProperty<RuleCashModel4>(_entities[7].properties[4]);

  /// see [RuleCashModel4.isIncome]
  static final isIncome =
      obx.QueryBooleanProperty<RuleCashModel4>(_entities[7].properties[5]);

  /// see [RuleCashModel4.cashType]
  static final cashType =
      obx.QueryIntegerProperty<RuleCashModel4>(_entities[7].properties[6]);
}

/// [ProductDiscountModel] entity fields to define ObjectBox queries.
class ProductDiscountModel_ {
  /// see [ProductDiscountModel.id]
  static final id = obx.QueryIntegerProperty<ProductDiscountModel>(
      _entities[8].properties[0]);

  /// see [ProductDiscountModel.idd]
  static final idd =
      obx.QueryStringProperty<ProductDiscountModel>(_entities[8].properties[1]);

  /// see [ProductDiscountModel.name]
  static final name =
      obx.QueryStringProperty<ProductDiscountModel>(_entities[8].properties[2]);

  /// see [ProductDiscountModel.typeName]
  static final typeName =
      obx.QueryStringProperty<ProductDiscountModel>(_entities[8].properties[3]);

  /// see [ProductDiscountModel.value]
  static final value =
      obx.QueryDoubleProperty<ProductDiscountModel>(_entities[8].properties[4]);

  /// see [ProductDiscountModel.typeId]
  static final typeId =
      obx.QueryStringProperty<ProductDiscountModel>(_entities[8].properties[5]);

  /// see [ProductDiscountModel.total]
  static final total =
      obx.QueryDoubleProperty<ProductDiscountModel>(_entities[8].properties[6]);
}

/// [ReceiptModelOFD4] entity fields to define ObjectBox queries.
class ReceiptModelOFD4_ {
  /// see [ReceiptModelOFD4.id]
  static final id =
      obx.QueryIntegerProperty<ReceiptModelOFD4>(_entities[9].properties[0]);

  /// see [ReceiptModelOFD4.receiptSeq]
  static final receiptSeq =
      obx.QueryIntegerProperty<ReceiptModelOFD4>(_entities[9].properties[1]);

  /// see [ReceiptModelOFD4.dateTime]
  static final dateTime =
      obx.QueryIntegerProperty<ReceiptModelOFD4>(_entities[9].properties[2]);

  /// see [ReceiptModelOFD4.terminalId]
  static final terminalId =
      obx.QueryStringProperty<ReceiptModelOFD4>(_entities[9].properties[3]);

  /// see [ReceiptModelOFD4.fiscalSign]
  static final fiscalSign =
      obx.QueryStringProperty<ReceiptModelOFD4>(_entities[9].properties[4]);
}
